# Wisp Shell - Kitty Configuration

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

window_padding_width 12

background_opacity 0.85
background_blur 1
hide_window_decorations yes

# Include the generated Matugen colors
include colors.conf
