[config]
version_check = false

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.discord]
input_path = 'templates/discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'

[templates.spotify]
input_path = 'templates/spotify.ini'
output_path = '~/.config/spicetify/Themes/Matugen/color.ini'

[templates.fastfetch]
input_path = 'templates/fastfetch-colors.jsonc'
output_path = '~/.config/fastfetch/colors.jsonc'

[templates.btop]
input_path = 'templates/btop-theme.theme'
output_path = '~/.config/btop/themes/wisp.theme'

[templates.starship]
input_path = 'templates/starship.toml'
output_path = '~/.config/starship.toml'
