$background = rgba({{colors.background.default.hex_stripped}}ff)
$surface = rgba({{colors.surface_container.default.hex_stripped}}ff)
$surface0 = rgba({{colors.surface_container_highest.default.hex_stripped}}ff)
$outline = rgba({{colors.outline_variant.default.hex_stripped}}ff)
$text = rgba({{colors.on_background.default.hex_stripped}}ff)
$subtext0 = rgba({{colors.on_surface_variant.default.hex_stripped}}ff)
$primary = rgba({{colors.primary.default.hex_stripped}}ff)
$on_primary = rgba({{colors.on_primary.default.hex_stripped}}ff)
$red = rgba({{colors.error.default.hex_stripped}}ff)

$active_border = rgba({{colors.primary.default.hex_stripped}}ff) rgba({{colors.primary_container.default.hex_stripped}}ff) 45deg
$inactive_border = rgba({{colors.surface_container_highest.default.hex_stripped}}ff)
