foreground #{{colors.on_background.default.hex_stripped}}
background #{{colors.background.default.hex_stripped}}
selection_foreground #{{colors.on_primary.default.hex_stripped}}
selection_background #{{colors.primary.default.hex_stripped}}
url_color #{{colors.primary.default.hex_stripped}}

color0  #{{colors.surface_container_highest.default.hex_stripped}}
color8  #{{colors.outline_variant.default.hex_stripped}}
color1  #{{colors.error.default.hex_stripped}}
color9  #{{colors.error.default.hex_stripped}}
color2  #{{colors.primary.default.hex_stripped}}
color10 #{{colors.primary.default.hex_stripped}}
color3  #{{colors.tertiary.default.hex_stripped}}
color11 #{{colors.tertiary.default.hex_stripped}}
color4  #{{colors.secondary.default.hex_stripped}}
color12 #{{colors.secondary.default.hex_stripped}}
color5  #{{colors.on_primary_container.default.hex_stripped}}
color13 #{{colors.on_primary_container.default.hex_stripped}}
color6  #{{colors.primary_container.default.hex_stripped}}
color14 #{{colors.primary_container.default.hex_stripped}}
color7  #{{colors.on_background.default.hex_stripped}}
color15 #{{colors.on_background.default.hex_stripped}}

cursor #{{colors.primary.default.hex_stripped}}
cursor_text_color #{{colors.on_primary.default.hex_stripped}}
